### ISSUE TITLE
Tal vez ha fallado el último despliegue

### ISSUE THREAD

**Issue by rachelcarmena** [npatarino/tech-conferences-spain#13]
Hola @npatarino !!

Disculpa que te moleste de nuevo, pero navegando por Comunidad Tecnológica, he accedido a tu web y he visto que **JS Camp** sigue en _happening_.

Los últimos cambios que aplicaste son correctos:
* He actualizado mi _workspace_ con tu rama _master_ y en local no se veía el evento como _happening_ :ok_hand: 
* He creado un repo desde 0 con el contenido de tu repo, he desplegado con GitHub Pages en mi cuenta y tampoco se veía el evento como _happening_ :ok_hand:  **Pero** sí que he tenido que eliminar `Gemfile.lock` porque aparecían unos avisos de vulnerabilidades de seguridad. Así no dependía de unas versiones concretas y se resolvían las dependencias en el despliegue. **Nota**: ya he eliminado esta última prueba de mi cuenta.

**Resumen**: probaría a eliminar el fichero `Gemfile.lock` para que se despliegue de nuevo y te desaparezcan los avisos de seguridad. Y al volverse a desplegar, debería desaparecer el evento **JS Camp** como _happening_.

**Comment by npatarino** [comment]
Es verdad! Está re-desplegado y ahora funciona correctamente!
Muchísimas gracias @rachelcarmena!

**Comment by rachelcarmena** [comment]
Genial!!! Siiiiii, ahora está :ok: Gracias a tiiiiiiiiiiiiiii!!! :tada:
