### ISSUE TITLE
Idea para mantenimiento

### ISSUE THREAD

**Issue by rachelcarmena** [npatarino/tech-conferences-spain#7]
Hola @npatarino,

En la guía de colaboración sólo indicas cómo añadir un evento, pero, tal vez, podría ser una buena idea indicar cómo actualizar un evento.

No sé si habías pensado en ello, pero una idea fácil podría ser que los ficheros de eventos no tengan año y se vayan actualizando conforme se tenga la información de la siguiente edición.

De este modo, no tienes que gestionar histórico. Si un evento no tiene segunda edición, se quedará siempre en "eventos pasados".

¿Qué te parece? Mi [PR](https://github.com/npatarino/tech-conferences-spain/pull/6) sigue esa idea. Faltaría ampliar la guía de colaboración para comentarlo. Y tal vez, también ayuda quitar la extensión `-2019` de todos los ficheros de eventos, para que se entienda que es "el fichero del evento" y no "el fichero de una edición determinada del evento".

¡¡Gracias!! :rocket:

**Comment by npatarino** [comment]
Buenas Rachel!
Primero que todo muchísimas gracias por el PR, la verdad que es una idea muy buena, sólo que en este caso creo que sí puede aportar el hecho de tener el histórico de eventos, así no sólo podríamos acceder a la web del T3chFest del año 2018 y ver las charlas allí publicadas y demás.
Uno de los puntos de este proyecto es tener registro de los próximos eventos y un histórico de los ya pasados, en un principio de forma simple sin darle mucha vuelta.
Te agradezco un montón el PR propuesto, aún así, creés que tiene sentido lo que comento de intentar mantener un histórico?

**Comment by rachelcarmena** [comment]
Oh, claro, tiene todo el sentido. ¡¡Buena idea!! Cierro PR y esto. ¡¡Gracias @npatarino!!  :clap:
